In [7]:
import numpy as np
import sys

In [3]:
listaA = [1, 2, 3, 4, 5]
listaB = np.array([1, 2, 3, 4, 5])

In [5]:
print(listaA) # mostra a lista com virgulas
print(listaB) # mostra a lista sem virgulas

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [15]:
sys.getsizeof('Lista python', listaA) # mostra o tamanho da lista em bytes

53

In [16]:
sys.getsizeof('Lista numpy', listaB) # mostra o tamanho da lista em bytes

52

In [19]:
listaA = list(range(1_000_000))
listaB = np.arange(1_000_000)

print('Lista python', sys.getsizeof(listaA))
print('Lista numpy', listaB.nbytes)

Lista python 8000056
Lista numpy 8000000


In [ ]:
tamanho_lista = sys.getsizeof(listaA) + sum(sys.getsizeof(x) for x in listaA)

print('Lista python', tamanho_lista)
print('Lista numpy', listaB.nbytes)

In [36]:
# Array 1D
# d = np.array([1,2,3]) # array de uma dimensão
# d = np.array([[1,2,3],[4,5,6]]) # array de duas dimensões
d = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(d)


#array 3d é como se fosse tabelas

# [
#     [                 # tabela 1
#         [1, 2],
#         [3, 4]
#     ],

#     [                 # tabela 2
#         [5, 6],
#         [7, 8]
#     ]
# ]




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
d.shape

(2, 2, 2)

In [33]:
d.ndim # numero de dimensões

3

In [34]:
d.dtype

dtype('int64')